#   config.yaml 
# Soil Erosion Modelling – LOAO Final Model Configuration


# Data and I/O
# ------------------------------------------------------------
data_dir: data/                      # Folder containing <area>.tif files
output_dir: output/Final_Model/      # Where model + scaler + predictions go

# ------------------------------------------------------------
# Study Areas
# Use either folder_mode OR the explicit list
study_areas:
  folder_mode: false
  list:
    - Adenstedt
    - Barum
    - Brueggen
    - Kleinilde
    - Kueingdorf
    - Lamspringe
    - Nette


# Bands to load from each .tif file
# Must match the layer descriptions inside the GeoTIFFs
bands:
  - B03_DEM1_res_5m
  - B04_Slope
  - B05_Aspect_360
  - B06_Aspect_180
  - B07_PlanCurv
  - B08_ProfileCurv
  - B09_FlowLineCurv
  - B10_DCI
  - B11_DCI10
  - B12_FA_fields
  - B13_SL_fields
  - B14_LS_factor_fields
  - B15_TPI
  - B16_WI
  - B17_K_factor
  - B18_R_factor
  - B19_C_factor
  - B20_MD
  - B21_MD_vs_Aspect


# Model selection
model_type: cnn

training:
  batch_size: 1028
  fixed_epochs: 50 
  seed: 42
  
# Final hyperparameters selected by grid search

# --------------- CNN ---------------
cnn:
  lr: 1e-5
  patch_size: 7
  conv_layers: 4
  filters: 256
  l2_conv: 1e-2
  l2_dense: 1e-5
  dropout: 0.0
  kernel_size: 5  

# --------------- DNN ---------------
dnn:
  lr: 1e-4
  layers: 3
  units: 256
  dropout: 0.25
  l2_dense: 1e-3

# --------------- SNN ---------------
snn:
  lr: 1e-3
  units: 512
  l2_dense: 1e-3

# --------------- Random Forest ---------------
rf:
  n_estimators: 400
  max_depth: 20
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "log2"

# ------------------------------------------------------------
# Neural network training settings
nn_training:
  batch_size: 1028
  epochs: 50
  patience: 8
  seed: 42

